config/routes.rb
Rails.application.routes.draw do

  resources :statistics do
    collection do
      get :data_grid
      get :chart
    end
  end

  resources :notifications do
    collection do
      get :notification
      get :read_all
      get :delete_all
      get :vencimento
      get :checkout
    end
  end

  resources :checkins

  resources :folders

  resources :documents do
    collection do
      get :checkout
      get :validar
      post :validar_create
      get :started
      get :create_started
      get :download
    end
  end

  resources :document_types

  resources :document_processes

  resource :sistem_configurations

  resources :user_groups do
    collection do
      match 'search' => 'user_groups#search', via: [:get, :post], as: :search
    end
  end

  resources :homepages do
    collection do
      get :search
    end
  end

  resources :users do
    collection do
      match 'search' => 'users#search', via: [:get, :post], as: :search
    end
  end

  devise_for :users, :path => 'contas', :path_names => { :sign_up => "registrar", :sign_in => "entrar" }, :controllers => { :sessions => 'sessions' }

  root to: "homepages#index"

end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  permissions :add=>{
    "user_group:index" => {
      :title => "Acessar Cadastro",
      :description => "Permite cadastrar novos documentos"
    },
  } ,:only=> [:new, :edit, :destroy]

  validates :name, presence: true, uniqueness: true

  has_many :permissions, :dependent => :delete_all
  accepts_nested_attributes_for :permissions

  has_many :users_user_groups
  has_many :users, through: :users_user_groups

  def save_permissions(codes)
    delete_permissions(codes)
    create_permissions(codes)
  end

  private

  def delete_permissions(codes)
    # apaga as permissões que não estão na lista passada
   permissions.where("permission_code not in (?)", codes).destroy_all unless codes.nil?
  end

  def create_permissions(codes)
    # Cria as permissões que estão na lista porém não estão no banco
    return if codes.nil?
    permission_codes = permissions.map(&:permission_code)
    codes.each do |permission_code|
      permissions.create(:permission_code => permission_code) unless permission_codes.include?(permission_code)
    end
  end
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  #before_action :set_user_group, only: [:show, :edit, :update, :destroy]
  after_filter :save_permissions, :only => [:create, :update]

  # GET /user_groups
  # GET /user_groups.json

  private
    def save_permissions
      @user_group.save_permissions(params[:permission_codes])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user_group
      @user_group = UserGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_group_params
      params.require(:user_group).permit(:name, :user_ids=>[])
    end
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/_form.html.erb
<%= simple_form_for(@user_group) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="panel panel-success">
    <div class="panel-heading">Usuários do grupo</div>
    <div class="panel-body">
      <div class="col-sm-12">
        <% User.all.each do |user| %>
          <div class="checkbox col-md-4">
            <label>
            <%= check_box_tag "user_group[user_ids][]", user.id, @user_group.users.include?(user) %>
            <%= user.name %>
            </label>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div>
    <%= render "permissions", :f=>f %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn-success" %>
  </div>
<% end %>

app/views/user_groups/_permissions.html.erb
<div class="panel panel-success">
  <div class="panel-heading">Permissões</div>
  <div class="panel-body">
    <div>
      <div id="permissoes" class="row" style="padding-left: 10px;">
        <% count = 0 %>
        <% PunditRoles::PERMISSIONS.sort.each do |model_name, permissions| %>
          <div class="col-sm-3">
            <%= I18n.t("permissions.models."+model_name) %>
            <% permissions.sort_by { |k,v| v[:title] || v }.map.each do |code, hash| %>
              <div class="checkbox">
                <label>
                  <%= check_box_tag "permission_codes[]", code,
                    @user_group.permissions.map(&:permission_code).include?(code) %>
                  <%= hash[:title] %>
                </label>
              </div>
            <% end %>
          </div>
          <% count = count + 1 %>
          <% if count % 4 == 0 %>
            <div %="" class="clearfix" style="border-bottom: 1px dashed; margin: 0px 0px 15px;"></div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user_groups/index.html.erb
<section class="invoice">

  <div class="row">
    <%= search_form_for @q, url: search_user_groups_path, html: { method: :post } do |f| %>
    <div class="col-lg-12">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.search_field :name_cont, class: "string form-control", label: false %>
      </div>
    </div>

    <div class="col-lg-12">
    <div class="form-action.search">
      <div class="pull-right">
        <%= link_to 'Limpar', user_groups_path, class: "btn btn-default" %>
        <%= f.submit :Pesquisar, class: "btn btn-success" %>
      </div>
      <% end %>
    </div>
    </div>
  </div>

  <hr />


  <div class="row">
    <div class="col-xs-12">
      <div class="box-body table-responsive">
        <table class="table table-hover">
          <thead>
            <th>Nome</th>
            <th class="action-table">
              <%= link_to new_user_group_path(@user_group), class:'btn btn-success'  do %>
                <span class="fa fa-plus"></span>
                Novo
              <% end if current_user.can?("usergroup:new") %>
            </th>
          </thead>
          <tbody>
            <%= content_tag_for(:tr, @user_groups) do |user_group| %>
              <td><%= user_group.name %></td>
              <td>
                <%= edit_buttom(edit_user_group_path(user_group), "usergroup:edit") %>
                <%= destroy_buttom(user_group, "usergroup:destroy") %>
              </td>
            <% end %>
          </tbody>
        </table>

        <%= render partial:"layouts/willpaginate", locals: { list:@user_groups } %>
      </div>
    </div>
  </div>
</section>

app/views/user_groups/show.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>Show <small>user_group</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><%= link_to "User_groups", user_groups_path %></li>
      <li class="active">Show</li>
    </ol>
  </section>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header">
          <div class="box-tools pull-right">
            <%= link_to edit_user_group_path(@user_group), :class => 'btn btn-primary' do %>
              <span class="glyphicon glyphicon-pencil"></span>
              Edit
            <% end %>          
          </div>
        </div>
        <div class="box-body">
          <dl class="dl-horizontal">
            <dt>Name:</dt>
            <dd><%= @user_group.name %></dd>

          </dl>
        </div>
      </div>
    </div>
  </div>
</section>