config/routes.rb
Rails.application.routes.draw do

  resources :statistics do
    collection do
      get :data_grid
      get :chart
    end
  end

  resources :notifications do
    collection do
      get :notification
      get :read_all
      get :delete_all
      get :vencimento
      get :checkout
    end
  end

  resources :checkins

  resources :folders

  resources :documents do
    collection do
      get :checkout
      get :validar
      post :validar_create
      get :started
      get :create_started
      get :download
    end
  end

  resources :document_types

  resources :document_processes

  resource :sistem_configurations

  resources :user_groups do
    collection do
      match 'search' => 'user_groups#search', via: [:get, :post], as: :search
    end
  end

  resources :homepages do
    collection do
      get :search
    end
  end

  resources :users do
    collection do
      match 'search' => 'users#search', via: [:get, :post], as: :search
    end
  end

  devise_for :users, :path => 'contas', :path_names => { :sign_up => "registrar", :sign_in => "entrar" }, :controllers => { :sessions => 'sessions' }

  root to: "homepages#index"

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :document
  belongs_to :user
  belongs_to :autor, class_name:"User", foreign_key: :autor_id

  scope :unread, -> { where(:read=>false) }

  attr_accessor :icon, :read
  after_initialize :set_icon

  def set_icon
    if read
      self.icon = "fa-check-square-o"
    else
      self.icon = "fa-square-o"
    end
  end

  def description
    read_attribute(:name)||"Vazia"
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    breadcrumb_for_actions
  end

  def show
    @notification = Notification.find(params[:id])

    @notification.update_attributes(read: true)
    add_breadcrumb get_model.model_name.human(count: 2), "/"+self.controller_path
    add_breadcrumb "Minhas Notificações", notification_notifications_path
    add_breadcrumb @notification.description[0..10]
  end

  def notification
    breadcrumb_for_actions("Minhas Notificações")

    @user_notifications = current_user.notifications.unread.paginate(:page => params[:page])
  end

  def vencimento
    breadcrumb_for_actions("Vencimentos")

    #@vencendo = Document.vencendo(current_user.id).paginate(:page => params[:page])
    @vencendo = Document.vencidos(current_user.id).paginate(:page => params[:page])
  end

  def checkout
    breadcrumb_for_actions("Documento aguardando validação")

    @documents = Document.aguardando_validacao(current_user.id).paginate(:page => params[:page])
  end

  def read_all
    get_current_user_unread_notification
    @current_user_notifications.update_all(read: true) if @current_user_notifications.any?
    redirect_to notification_notifications_path
  end

  def delete_all
    get_current_user_unread_notification
    @current_user_notifications.delete_all if @current_user_notifications.any?
    redirect_to notification_notifications_path
  end

  private
  def get_current_user_unread_notification
    @current_user_notifications = current_user.notifications.unread
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification_paginate.html.erb
<!-- Check all button -->
<div class="btn-group">
  <%= link_to read_all_notifications_path do %>
    <button class="btn btn-default btn-sm" title="Ler todas"><i class="fa fa-child"></i></button>
  <% end %>
  <%= link_to delete_all_notifications_path do %>
    <button class="btn btn-default btn-sm" title="Esvaziar"><i class="fa fa-trash-o"></i></button>
  <% end %>
</div><!-- /.btn-group -->
<%= link_to notification_notifications_path do %>
  <button class="btn btn-default btn-sm"><i class="fa fa-refresh"></i></button>
<% end %>
<div class="pull-right">
  <%= page_entries_info @user_notifications %>
  <%= will_paginate @user_notifications %>
  <div class="btn-group">
    <button class="btn btn-default btn-sm"><i class="fa fa-chevron-left"></i></button>
    <button class="btn btn-default btn-sm"><i class="fa fa-chevron-right"></i></button>
  </div><!-- /.btn-group -->
</div><!-- /.pull-right -->

app/views/notifications/_side_box.html.erb
<div class="box box-solid">
  <div class="box-header with-border">
    <h3 class="box-title">Dashboard</h3>
  </div>
  <div class="box-body no-padding">
    <ul class="nav nav-pills nav-stacked">
      <li class=<%= "active" if controller.action_name == "notification" %>>
        <%= link_to  notification_notifications_path  do %>
          <i class="fa fa-envelope-o"></i> Notificações
          <%= content_tag(:span, @notifications, class: "label label-primary pull-right") if @notifications>0 %>
        <% end %>
      </li>
      <li class=<%= "active" if controller.action_name == "checkout" %>>
        <%= link_to checkout_notifications_path  do %>
          <i class="fa fa-file-text-o"></i> Aguardando validação
          <%= content_tag(:span, @checkouts, class: "label label-primary pull-right") if @checkouts>0 %>
        <% end %>
      </li>
      <li class=<%= "active" if controller.action_name == "vencimento" %> >
        <%= link_to vencimento_notifications_path  do %>
          <i class="fa fa-calendar"></i> Vencimento
          <%= content_tag(:span, @vencimentos, class: "label label-primary pull-right") if @vencimentos>0 %>
        <% end %>
      </li>
    </ul>
  </div><!-- /.box-body -->
</div><!-- /. box -->

app/views/notifications/checkout.html.erb
<section class="content">
  <div class="row">
    <div class="col-md-3">
      <a href="compose.html" class="btn btn-primary btn-block margin-bottom">Notificação</a>
      <%= render "side_box" %>
    </div><!-- /.col -->
    <div class="col-md-9">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Documentos</h3>
        </div><!-- /.box-header -->
        <div class="box-body no-padding">
          <div class="table-responsive mailbox-messages">
            <table class="table table-hover table-striped">
              <tbody>
                <% @documents.each do |document| %>
                <tr>
                  <td class="mailbox-star">
                    <%= link_to "<i class='fa #{document.icon} text-yellow'></i>".html_safe, validar_documents_path(id:document.id) %>
                  </td>
                  <td class="mailbox-name"><%= link_to document.name, validar_documents_path(id:document.id) %></td>
                  <td class="mailbox-subject"><b><%= document.user.name %></b></td>
                  <td class="mailbox-attachment"></td>
                  <td class="mailbox-date"><%= document.created_at %></td>
                </tr>
                <% end %>
              </tbody>
            </table><!-- /.table -->
          </div><!-- /.mail-box-messages -->
        </div><!-- /.box-body -->
        <div class="box-footer no-padding">
          <div class="mailbox-controls">
            <div>
              <%= page_entries_info @documents  %>
              <%= will_paginate @documents, renderer: BootstrapPagination::Rails %>
            </div><!-- /.pull-right -->
          </div>
        </div>
      </div><!-- /. box -->
    </div>
  </div>
</section>

app/views/notifications/index.html.erb
<section class="content">
  <div class="row">
    <div class="col-md-3">
      <a href="compose.html" class="btn btn-primary btn-block margin-bottom">Notificação</a>
      <%= render "side_box" %>
    </div><!-- /.col -->
    <div class="col-md-9">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Inbox</h3>
          <div class="box-tools pull-right">
            <div class="has-feedback">
              <input type="text" class="form-control input-sm" placeholder="Search Mail">
              <span class="glyphicon glyphicon-search form-control-feedback"></span>
            </div>
          </div><!-- /.box-tools -->
        </div><!-- /.box-header -->
        <div class="box-body no-padding">
          <div class="mailbox-controls">
            <!-- Check all button -->
            <button class="btn btn-default btn-sm checkbox-toggle"><i class="fa fa-square-o"></i></button>
            <div class="btn-group">
              <button class="btn btn-default btn-sm"><i class="fa fa-trash-o"></i></button>
              <button class="btn btn-default btn-sm"><i class="fa fa-reply"></i></button>
              <button class="btn btn-default btn-sm"><i class="fa fa-share"></i></button>
            </div><!-- /.btn-group -->
            <button class="btn btn-default btn-sm"><i class="fa fa-refresh"></i></button>
            <div class="pull-right">
              1-50/200
              <div class="btn-group">
                <button class="btn btn-default btn-sm"><i class="fa fa-chevron-left"></i></button>
                <button class="btn btn-default btn-sm"><i class="fa fa-chevron-right"></i></button>
              </div><!-- /.btn-group -->
            </div><!-- /.pull-right -->
          </div>
          <div class="table-responsive mailbox-messages">
            <table class="table table-hover table-striped">
              <tbody>
                <tr>
                  <td><div class="icheckbox_flat-blue" aria-checked="false" aria-disabled="false" style="position: relative;"><input type="checkbox" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);"></ins></div></td>
                  <td class="mailbox-star"><a href="#"><i class="fa fa-star text-yellow"></i></a></td>
                  <td class="mailbox-name"><a href="read-mail.html">Alexander Pierce</a></td>
                  <td class="mailbox-subject"><b>AdminLTE 2.0 Issue</b> - Trying to find a solution to this problem...</td>
                  <td class="mailbox-attachment"></td>
                  <td class="mailbox-date">5 mins ago</td>
                </tr>
                <tr>
                  <td><div class="icheckbox_flat-blue" aria-checked="false" aria-disabled="false" style="position: relative;"><input type="checkbox" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);"></ins></div></td>
                  <td class="mailbox-star"><a href="#"><i class="fa fa-star-o text-yellow"></i></a></td>
                  <td class="mailbox-name"><a href="read-mail.html">Alexander Pierce</a></td>
                  <td class="mailbox-subject"><b>AdminLTE 2.0 Issue</b> - Trying to find a solution to this problem...</td>
                  <td class="mailbox-attachment"><i class="fa fa-paperclip"></i></td>
                  <td class="mailbox-date">28 mins ago</td>
                </tr>
              </tbody>
            </table><!-- /.table -->
          </div><!-- /.mail-box-messages -->
        </div><!-- /.box-body -->
        <div class="box-footer no-padding">
          <div class="mailbox-controls">
            <!-- Check all button -->
            <button class="btn btn-default btn-sm checkbox-toggle"><i class="fa fa-square-o"></i></button>
            <div class="btn-group">
              <button class="btn btn-default btn-sm"><i class="fa fa-trash-o"></i></button>
              <button class="btn btn-default btn-sm"><i class="fa fa-reply"></i></button>
              <button class="btn btn-default btn-sm"><i class="fa fa-share"></i></button>
            </div><!-- /.btn-group -->
            <button class="btn btn-default btn-sm"><i class="fa fa-refresh"></i></button>
            <div class="pull-right">
              1-50/200
              <div class="btn-group">
                <button class="btn btn-default btn-sm"><i class="fa fa-chevron-left"></i></button>
                <button class="btn btn-default btn-sm"><i class="fa fa-chevron-right"></i></button>
              </div><!-- /.btn-group -->
            </div><!-- /.pull-right -->
          </div>
        </div>
      </div><!-- /. box -->
    </div><!-- /.col -->
  </div><!-- /.row -->
</section>

app/views/notifications/notification.html.erb
<section class="content">
  <div class="row">
    <div class="col-md-3">
      <a href="compose.html" class="btn btn-primary btn-block margin-bottom">Notificação</a>
      <%= render "side_box" %>
    </div><!-- /.col -->
    <div class="col-md-9">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Notificações</h3>
          <!-- /<div class="box-tools pull-right">
            <div class="has-feedback">
              <input type="text" class="form-control input-sm" placeholder="Search Mail">
              <span class="glyphicon glyphicon-search form-control-feedback"></span>
            </div>
          </div>.box-tools -->
        </div><!-- /.box-header -->
        <div class="box-body no-padding">
          <div class="mailbox-controls">
            <%= render "notification_paginate" %>
          </div>
          <div class="table-responsive mailbox-messages">
            <table class="table table-hover table-striped">
              <tbody>
                <% @user_notifications.each do |notify| %>
                <tr>
                  <td class="mailbox-star"><a href="#"><i class="fa <%= notify.icon %> text-yellow"></i></a></td>
                  <td class="mailbox-subject"><b><%= link_to notify.autor.name, notification_path(notify) %></b></td>
                  <td class="mailbox-name"><%= link_to notify.description, notification_path(notify) %></td>
                  <td class="mailbox-attachment"></td>
                  <td class="mailbox-date"><%= notify.created_at %></td>
                </tr>
                <% end %>
                <% if @user_notifications.blank? %>
                <tr>
                  <td>Notificações não lidas 0</td>
                </tr>
                <% end %>
              </tbody>
            </table><!-- /.table -->
          </div><!-- /.mail-box-messages -->
        </div><!-- /.box-body -->
        <div class="box-footer no-padding">
          <div class="mailbox-controls">
            <%= render "notification_paginate" %>
          </div>
        </div>
      </div><!-- /. box -->
    </div>
  </div>
</section>

app/views/notifications/show.html.erb
<div class="col-md-12">
  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Ler Notificação</h3>
      <div class="box-tools pull-right">
        <a href="#" class="btn btn-box-tool" data-toggle="tooltip" title="" data-original-title="Previous"><i class="fa fa-chevron-left"></i></a>
        <a href="#" class="btn btn-box-tool" data-toggle="tooltip" title="" data-original-title="Next"><i class="fa fa-chevron-right"></i></a>
      </div>
    </div><!-- /.box-header -->
    <div class="box-body no-padding">
      <div class="mailbox-read-info">
        <h3><%= @notification.autor.name %></h3>
        <h5>De: <%= @notification.autor.email %> <span class="mailbox-read-time pull-right"> <%= @notification.created_at %></span></h5>
      </div><!-- /.mailbox-read-info -->

      <div class="mailbox-read-message" style="min-height: 300px;">
        <p><%= @notification.description %></p>
      </div><!-- /.mailbox-read-message -->
    </div><!-- /.box-body -->
    <div class="box-footer">
      <% if @notification.document.present? %>
      <ul class="mailbox-attachments clearfix">
        <li>
          <span class="mailbox-attachment-icon"><i class="fa fa-file-pdf-o"></i></span>
          <div class="mailbox-attachment-info">
            <a href="#" class="mailbox-attachment-name"><i class="fa fa-paperclip"></i> <%= @notification.document.arquivo_file_name %> </a>
            <span class="mailbox-attachment-size">
              <%= @notification.document.arquivo_file_size %>
              <%= link_to @notification.document.arquivo.url, class:"btn btn-default btn-xs pull-right" do %>
                <i class="fa fa-cloud-download"></i>
              <% end %>
            </span>
          </div>
        </li>
      </ul>
      <% end %>
    </div><!-- /.box-footer -->
    <div class="box-footer">
      <div class="pull-right">
      </div>
      <%= link_to notification_path(@notification), method: :delete do %>
        <button class="btn btn-default"><i class="fa fa-trash-o"></i> Excluir</button>
      <% end %>
      <button class="btn btn-default"><i class="fa fa-print"></i> Imprimir</button>
    </div><!-- /.box-footer -->
  </div><!-- /. box -->
</div>

app/views/notifications/vencimento.html.erb
<section class="content">
  <div class="row">
    <div class="col-md-3">
      <a href="compose.html" class="btn btn-primary btn-block margin-bottom">Notificação</a>
      <%= render "side_box" %>
    </div><!-- /.col -->
      <div class="col-md-9">
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Documentos vencidos</h3>
            <!-- /<div class="box-tools pull-right">
              <div class="has-feedback">
                <input type="text" class="form-control input-sm" placeholder="Search Mail">
                <span class="glyphicon glyphicon-search form-control-feedback"></span>
              </div>
            </div>.box-tools -->
          </div><!-- /.box-header -->
          <div class="box-body no-padding">
            <div class="mailbox-controls">
              <%#= render "notification_paginate" %>
            </div>
            <div class="table-responsive mailbox-messages">
              <table class="table table-hover table-striped">
                <thead>
                  <th></th>
                  <th>Autor</th>
                  <th>Titulo</th>
                  <th>Validade</th>
                  <th>Data de notificação</th>
                </thead>
                <tbody>
                  <% @vencendo.each do |document| %>
                  <tr>
                    <td class="mailbox-star">
                      <%= link_to "<i class='fa #{document.icon} text-yellow'></i>".html_safe, document_path(document), title:"Visualizar" %>
                    </td>
                    <td class="mailbox-subject"><b><%= document.user.name %></b></td>
                    <td class="mailbox-name"><%= document.name %></td>
                    <td class="mailbox-attachment"><%= (document.date_validity).to_s_br %></td>
                    <td class="mailbox-date"><%= (document.date_validity + document.notification_period.to_i.days).to_s_br %></td>
                  </tr>
                  <% end %>
                </tbody>
              </table><!-- /.table -->
            </div><!-- /.mail-box-messages -->
          </div><!-- /.box-body -->
          <div class="box-footer no-padding">
            <div class="mailbox-controls">
              <%= page_entries_info @vencendo  %>
              <%= will_paginate @vencendo, renderer: BootstrapPagination::Rails %>
            </div>
          </div>
        </div><!-- /. box -->
      </div>
      </div>
</section>