config/routes.rb
Rails.application.routes.draw do

  resources :statistics do
    collection do
      get :data_grid
      get :chart
    end
  end

  resources :notifications do
    collection do
      get :notification
      get :read_all
      get :delete_all
      get :vencimento
      get :checkout
    end
  end

  resources :checkins

  resources :folders

  resources :documents do
    collection do
      get :checkout
      get :validar
      post :validar_create
      get :started
      get :create_started
      get :download
    end
  end

  resources :document_types

  resources :document_processes

  resource :sistem_configurations

  resources :user_groups do
    collection do
      match 'search' => 'user_groups#search', via: [:get, :post], as: :search
    end
  end

  resources :homepages do
    collection do
      get :search
    end
  end

  resources :users do
    collection do
      match 'search' => 'users#search', via: [:get, :post], as: :search
    end
  end

  devise_for :users, :path => 'contas', :path_names => { :sign_up => "registrar", :sign_in => "entrar" }, :controllers => { :sessions => 'sessions' }

  root to: "homepages#index"

end

app/controllers/document_processes_controller.rb
class DocumentProcessesController < ApplicationController

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def document_process_params
      params.require(:document_process).permit(:name,
        document_types_process_attributes: [:id, :_destroy, :document_type_id,
        document_type_attributes: [:id, :name, :_destroy]])
    end
end

app/views/document_processes/_document_type_fields.html.erb
<div class='nested-fields'>
  <%= f.input :name, label: 'Tipo de documento' %>
</div>

app/views/document_processes/_document_types_document_process_fields.html.erb
<div class="nested-fields relation-fields row">
  <div id="document_type_from_list"  class="col-md-8">
    <%= f.association :document_type, collection: DocumentType.all, label: "Tipo de documento" %>
  </div>
  <div class="col-md-4">
    <%= link_to_add_association 'Criar tipo documento', f, :document_type, class:"btn btn-info" %>
    <%= link_to_remove_association "<i class='fa fa-close'></i> Remover".html_safe, f, class:"btn btn-danger pullright" %>
  </div>
</div>

app/views/document_processes/_form.html.erb
<%= simple_form_for(@document_process) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div id="document_types">
    <%= f.simple_fields_for :document_types_document_process do |document_type| %>
      <%= render 'document_types_document_process_fields', f: document_type %>
    <% end %>

    <%= link_to_add_association "<i class='fa fa-plus'></i> Tipo de documento".html_safe, f, :document_types_document_process, class: "btn btn-info" %>
  </div>

  <div class="form-actions link">
    <%= f.button :submit, class: "btn-success" %>
  </div>
<% end %>

app/views/document_processes/edit.html.erb
<section class="content invoice">
  <%= render 'form' %>
</section>

app/views/document_processes/index.html.erb
<section class="content invoice">
  <div class="row">
    <div class="col-xs-12">
      <div class="box-body table-responsive">
        <table class="table table-hover">
          <thead>
            <th>Nome</th>
            <th>Quantidade de documentos</th>
            <th class="action-table">
              <%= link_to new_document_process_path(@document_processes), class:'btn btn-success'  do %>
                <span class="fa fa-plus"></span>
                  Novo
              <% end if current_user.can?('documentprocess:new') %>
            </th>
          </thead>
          <tbody>
            <%= content_tag_for(:tr, @document_processes) do |process| %>
              <td><%= process.name %></td>
              <td><%= process.document_types.size %></td>
              <td>
                <%= edit_buttom(edit_document_process_path(process), "documentprocess:edit") %>
                <%= destroy_buttom(process, "documentprocess:destroy") %>
              </td>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>

app/views/document_processes/new.html.erb
<section class="content invoice">
  <%= render 'form' %>
</section>

app/views/document_processes/show.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>Show <small>process</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><%= link_to "process", process_path %></li>
      <li class="active">Show</li>
    </ol>
  </section>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header">
          <div class="box-tools pull-right">
            <%= link_to edit_process_path(@process), :class => 'btn btn-primary' do %>
              <span class="glyphicon glyphicon-pencil"></span>
              Edit
            <% end %>
          </div>
        </div>
        <div class="box-body">
          <dl class="dl-horizontal">
            <dt>String:</dt>
            <dd><%= @process.string %></dd>

          </dl>
        </div>
      </div>
    </div>
  </div>
</section>